function cfg = fpc_coil_validate_config(cfg)
%FPC_COIL_VALIDATE_CONFIG Validate and normalize a complete configuration.

if ~isstruct(cfg) || ~isscalar(cfg)
    error('FPC_Coil:InvalidConfig', 'cfg must be a scalar struct.');
end

required = fieldnames(fpc_coil_default_config());
for k = 1:numel(required)
    if ~isfield(cfg, required{k})
        error('FPC_Coil:MissingConfigField', ...
            'cfg is missing required field "%s".', required{k});
    end
end

scalarNumeric = { ...
    'layerCount', 'maxLayerCount', 'turnsPerLayer', ...
    'plateLength', 'plateWidth', 'plateCornerRadius', ...
    'tabLength', 'tabWidth', 'tabOuterCornerRadius', ...
    'tabTransitionRadius', 'tabEdgeMargin', ...
    'traceWidth', 'traceSpacing', 'pitchMargin', 'edgeClearance', ...
    'minInnerWidth', 'minSpiralCornerRadius', ...
    'leadYOffset', 'leadBendRadius', 'leadArcPointCount', ...
    'padTipInset', 'padDiameter', 'padTipMargin', 'leadTabClearance', ...
    'padToPadClearance', 'padToCopperClearance', ...
    'viaDrillDiameter', 'viaPadDiameter', ...
    'viaToCopperClearance', 'viaToBoardClearance', ...
    'viaToViaClearance', 'viaToPadClearance', ...
    'viaLandingLeadLength', 'viaLandingClearance', 'viaInnerBendRadius', ...
    'viaOuterLandingLeadLength', 'viaOuterLandingClearance', ...
    'viaOuterBendRadius', 'outputViaTipInset', ...
    'outputViaAntiPadDiameter', 'outputViaToCopperClearance', ...
    'outputViaToBoardClearance', 'outputReturnBendRadius', ...
    'copperThickness', 'copperResistivity', 'minAnnularRing', ...
    'manufacturingTolerance', 'minCopperInteriorAngleDeg', ...
    'minBoardInteriorAngleDeg', 'angleToleranceDeg', ...
    'geometryTolerance', 'connectionTolerance', 'clearanceTolerance', ...
    'crossProductTolerance', 'parameterTolerance', ...
    'pointsPerTurn', 'minTurnPointCount', 'boardArcPointCount', ...
    'maxVerticesPerDxfEntity', 'previewDpi'};
for k = 1:numel(scalarNumeric)
    validateattributes(cfg.(scalarNumeric{k}), {'numeric'}, ...
        {'scalar', 'real', 'finite'}, mfilename, scalarNumeric{k});
end

if cfg.layerCount < 2 || cfg.layerCount ~= floor(cfg.layerCount) || ...
        mod(cfg.layerCount, 2) ~= 0 || cfg.layerCount > cfg.maxLayerCount
    error('FPC_Coil:InvalidLayerCount', ...
        ['layerCount=%g is invalid; layerCount must be an even value ', ...
         '(偶数) from 2 through maxLayerCount=%g.'], ...
        cfg.layerCount, cfg.maxLayerCount);
end
if cfg.maxLayerCount < 2 || cfg.maxLayerCount ~= floor(cfg.maxLayerCount) || ...
        mod(cfg.maxLayerCount, 2) ~= 0
    error('FPC_Coil:InvalidLayerCount', ...
        'maxLayerCount=%g must be an even value (偶数) of at least 2.', ...
        cfg.maxLayerCount);
end
if cfg.turnsPerLayer < 1 || cfg.turnsPerLayer ~= floor(cfg.turnsPerLayer)
    error('FPC_Coil:InvalidTurns', 'turnsPerLayer must be a positive integer.');
end

positive = {'plateLength','plateWidth','tabLength','tabWidth','traceWidth', ...
    'minInnerWidth','leadYOffset','leadBendRadius','padTipInset', ...
    'padDiameter','viaDrillDiameter','viaPadDiameter', ...
    'viaLandingLeadLength','viaInnerBendRadius', ...
    'viaOuterLandingLeadLength','viaOuterBendRadius', ...
    'outputViaTipInset','outputReturnBendRadius','copperThickness', ...
    'copperResistivity','geometryTolerance','connectionTolerance', ...
    'crossProductTolerance','parameterTolerance','pitchMargin','previewDpi'};
for k = 1:numel(positive)
    if cfg.(positive{k}) <= 0
        error('FPC_Coil:InvalidConfigValue', 'cfg.%s must be greater than zero.', positive{k});
    end
end

nonnegative = {'plateCornerRadius','tabOuterCornerRadius','tabEdgeMargin', ...
    'traceSpacing','edgeClearance','padTipMargin','leadTabClearance', ...
    'padToPadClearance','padToCopperClearance','viaToCopperClearance', ...
    'viaToBoardClearance','viaToViaClearance','viaToPadClearance', ...
    'viaLandingClearance','viaOuterLandingClearance', ...
    'outputViaToCopperClearance','outputViaToBoardClearance', ...
    'minAnnularRing','manufacturingTolerance','clearanceTolerance'};
for k = 1:numel(nonnegative)
    if cfg.(nonnegative{k}) < 0
        error('FPC_Coil:InvalidConfigValue', 'cfg.%s cannot be negative.', nonnegative{k});
    end
end

if cfg.viaPadDiameter <= cfg.viaDrillDiameter || ...
        (cfg.viaPadDiameter - cfg.viaDrillDiameter)/2 < cfg.minAnnularRing
    error('FPC_Coil:InvalidViaGeometry', ...
        'Via pad/drill dimensions do not provide minAnnularRing.');
end
if cfg.outputViaAntiPadDiameter <= cfg.viaPadDiameter
    error('FPC_Coil:InvalidViaGeometry', ...
        'outputViaAntiPadDiameter must exceed viaPadDiameter.');
end
if ~strcmp(cfg.outputViaType, 'through_via')
    error('FPC_Coil:InvalidOutputViaType', ...
        'outputViaType must be ''through_via'' for the L%d-to-L1 output.', cfg.layerCount);
end
if ~ismember(cfg.viaClearanceSeverity, {'warning','error'})
    error('FPC_Coil:InvalidSeverity', ...
        'viaClearanceSeverity must be ''warning'' or ''error''.');
end

integerAtLeast = { ...
    'leadArcPointCount', 8; 'pointsPerTurn', 100; ...
    'minTurnPointCount', 100; 'boardArcPointCount', 8; ...
    'maxVerticesPerDxfEntity', 2};
for k = 1:size(integerAtLeast, 1)
    name = integerAtLeast{k,1};
    lowerBound = integerAtLeast{k,2};
    if cfg.(name) < lowerBound || cfg.(name) ~= floor(cfg.(name))
        error('FPC_Coil:InvalidConfigValue', ...
            'cfg.%s must be an integer >= %d.', name, lowerBound);
    end
end

booleanFields = {'useRecommendedTurns','enablePreview', ...
    'requireSmoothEscapeArcs', ...
    'enableExactSelfIntersectionCheck','enableCopperClearanceCheck', ...
    'enableBoardAngleCheck','enableCopperAngleCheck', ...
    'enablePadClearanceCheck','enableViaClearanceCheck', ...
    'enableDxfReadbackCheck'};
for k = 1:numel(booleanFields)
    value = cfg.(booleanFields{k});
    if ~isscalar(value) || (~islogical(value) && ...
            ~(isnumeric(value) && ismember(value, [0, 1])))
        error('FPC_Coil:InvalidConfigValue', ...
            'cfg.%s must be logical or numeric 0/1.', booleanFields{k});
    end
    cfg.(booleanFields{k}) = logical(value);
end

if ~isTextScalar(cfg.outputRoot) || ~isTextScalar(cfg.designName)
    error('FPC_Coil:InvalidOutputName', ...
        'outputRoot and designName must be character vectors or string scalars.');
end
cfg.outputRoot = char(cfg.outputRoot);
cfg.designName = char(cfg.designName);
if isempty(cfg.outputRoot) || isempty(cfg.designName) || ...
        isempty(regexp(cfg.designName, '^[A-Za-z0-9_-]+$', 'once'))
    error('FPC_Coil:InvalidOutputName', ...
        'outputRoot must be nonempty and designName may contain only letters, numbers, _ and -.');
end

end

function tf = isTextScalar(value)

tf = ischar(value) || (isstring(value) && isscalar(value));

end
