function tests = test_rectangular_fpc_private_contracts
% Direct contracts for private manufacturing decisions.
tests = functiontests(localfunctions);
end

function testSupportedProfileRejectsAdjacentLayerVia(testCase)
result = rectangular_fpc_main(struct( ...
    'analysisOnly', true, ...
    'layerCount', 4, ...
    'turnsPerLayer', 1, ...
    'enablePreview', false, ...
    'enableFigure', false));
manufacturingInput = struct( ...
    'minCopperSpacing', result.validation.minCopperSpacingMm, ...
    'minCopperToBoardMm', result.validation.minCopperToBoardMm, ...
    'minPadToUnrelatedTraceMm', result.validation.minPadToUnrelatedTraceMm, ...
    'minViaToUnrelatedCopperMm', result.validation.minViaToUnrelatedCopperMm, ...
    'minDrillToNonConnectedCopperMm', ...
        result.validation.minDrillToNonConnectedCopperMm, ...
    'minDrillToBoardMm', result.validation.minDrillToBoardMm, ...
    'vias', result.vias, ...
    'viaNonConnectedCopperPassed', ...
        result.validation.viaNonConnectedCopperPassed);

baseline = rectangular_fpc_manufacturing( ...
    'check_result', result.config, manufacturingInput);
baselineTechnology = baseline.checks( ...
    strcmp({baseline.checks.id}, 'VIA_TECHNOLOGY'));
assertNumElements(testCase, baselineTechnology, 1);
verifyEqual(testCase, baselineTechnology.status, 'PASS');

manufacturingInput.vias(1).type = 'adjacent_layer_via';

report = rectangular_fpc_manufacturing( ...
    'check_result', result.config, manufacturingInput);
viaTechnology = report.checks(strcmp({report.checks.id}, 'VIA_TECHNOLOGY'));

assertNumElements(testCase, viaTechnology, 1);
verifyEqual(testCase, viaTechnology.status, 'FAIL');
verifyEqual(testCase, viaTechnology.code, 'UNSUPPORTED_VIA_TECHNOLOGY');
verifyFalse(testCase, report.exportAllowed);
verifyFalse(testCase, report.verified);
end

function testCheckResultRejectsMissingCopperToBoardMeasurement(testCase)
% P2 契约：check_result 缺少实测 minCopperToBoardMm 时必须 fail closed，
% 不允许静默回退到 cfg.edgeClearance（防止再次引入 H2 假 PASS）。
result = rectangular_fpc_main(struct( ...
    'analysisOnly', true, ...
    'layerCount', 2, ...
    'turnsPerLayer', 1, ...
    'enablePreview', false, ...
    'enableFigure', false));
manufacturingInput = struct( ...
    'minCopperSpacing', result.validation.minCopperSpacingMm, ...
    'minCopperToBoardMm', result.validation.minCopperToBoardMm, ...
    'minPadToUnrelatedTraceMm', result.validation.minPadToUnrelatedTraceMm, ...
    'minViaToUnrelatedCopperMm', result.validation.minViaToUnrelatedCopperMm, ...
    'minDrillToNonConnectedCopperMm', ...
        result.validation.minDrillToNonConnectedCopperMm, ...
    'vias', result.vias, ...
    'viaNonConnectedCopperPassed', ...
        result.validation.viaNonConnectedCopperPassed);
verifyError(testCase, @() rectangular_fpc_manufacturing( ...
    'check_result', result.config, manufacturingInput), ...
    'RectangularFPC:ManufacturingInputContract');
end

function testCheckResultUsesMeasuredClearancesAndFailsBelowRule(testCase)
result = rectangular_fpc_main(struct( ...
    'analysisOnly', true, 'layerCount', 2, 'turnsPerLayer', 1, ...
    'enablePreview', false, 'enableFigure', false));
input = struct( ...
    'minCopperSpacing', result.validation.minCopperSpacingMm, ...
    'minCopperToBoardMm', result.validation.minCopperToBoardMm, ...
    'minPadToUnrelatedTraceMm', result.validation.minPadToUnrelatedTraceMm, ...
    'minViaToUnrelatedCopperMm', result.validation.minViaToUnrelatedCopperMm, ...
    'minDrillToNonConnectedCopperMm', ...
        result.validation.minDrillToNonConnectedCopperMm, ...
    'minDrillToBoardMm', result.validation.minDrillToBoardMm, ...
    'vias', result.vias, ...
    'viaNonConnectedCopperPassed', ...
        result.validation.viaNonConnectedCopperPassed);
report = rectangular_fpc_manufacturing( ...
    'check_result', result.config, input);
padRow = report.checks(strcmp({report.checks.id}, 'PAD_TO_TRACE'));
viaRow = report.checks(strcmp({report.checks.id}, 'VIA_TO_TRACE'));
drillCopperRow = report.checks(strcmp({report.checks.id}, 'DRILL_TO_COPPER'));
drillBoardRow = report.checks(strcmp({report.checks.id}, 'DRILL_TO_BOARD'));
verifyEqual(testCase, padRow.measuredMm, ...
    result.validation.minPadToUnrelatedTraceMm, 'AbsTol', 1e-9);
verifyEqual(testCase, viaRow.measuredMm, ...
    result.validation.minViaToUnrelatedCopperMm, 'AbsTol', 1e-9);
verifyEqual(testCase, drillCopperRow.measuredMm, ...
    result.validation.minDrillToNonConnectedCopperMm, 'AbsTol', 1e-9);
verifyEqual(testCase, drillBoardRow.measuredMm, ...
    result.validation.minDrillToBoardMm, 'AbsTol', 1e-9);

input.minPadToUnrelatedTraceMm = report.rules.minPadToTraceMm - 0.001;
badReport = rectangular_fpc_manufacturing( ...
    'check_result', result.config, input);
badPadRow = badReport.checks(strcmp({badReport.checks.id}, 'PAD_TO_TRACE'));
verifyEqual(testCase, badPadRow.status, 'FAIL');
verifyFalse(testCase, badReport.passed);
end

function testCheckResultRejectsIncompleteManufacturingInput(testCase)
% L1 回归：check_result 输入契约覆盖全部实测字段，缺任一即 fail closed；
% 尤其缺 vias 时不得静默跳过 VIA_TECHNOLOGY 资格行。
result = rectangular_fpc_main(struct( ...
    'analysisOnly', true, 'layerCount', 2, 'turnsPerLayer', 1, ...
    'enablePreview', false, 'enableFigure', false));
base = struct( ...
    'minCopperSpacing', result.validation.minCopperSpacingMm, ...
    'minCopperToBoardMm', result.validation.minCopperToBoardMm, ...
    'minPadToUnrelatedTraceMm', result.validation.minPadToUnrelatedTraceMm, ...
    'minViaToUnrelatedCopperMm', result.validation.minViaToUnrelatedCopperMm, ...
    'minDrillToNonConnectedCopperMm', ...
        result.validation.minDrillToNonConnectedCopperMm, ...
    'minDrillToBoardMm', result.validation.minDrillToBoardMm, ...
    'vias', result.vias, ...
    'viaNonConnectedCopperPassed', result.validation.viaNonConnectedCopperPassed);
missingSpacing = rmfield(base, 'minCopperSpacing');
missingBoard = rmfield(base, 'minCopperToBoardMm');
missingPadTrace = rmfield(base, 'minPadToUnrelatedTraceMm');
missingViaCopper = rmfield(base, 'minViaToUnrelatedCopperMm');
missingDrillCopper = rmfield(base, 'minDrillToNonConnectedCopperMm');
missingDrillBoard = rmfield(base, 'minDrillToBoardMm');
missingVias = rmfield(base, 'vias');
missingVerdict = rmfield(base, 'viaNonConnectedCopperPassed');
emptyVias = base;
emptyVias.vias = struct([]);
cases = {missingSpacing, missingBoard, missingPadTrace, missingViaCopper, ...
    missingDrillCopper, missingDrillBoard, missingVias, missingVerdict, emptyVias};
for caseIndex = 1:numel(cases)
    verifyError(testCase, @() rectangular_fpc_manufacturing( ...
        'check_result', result.config, cases{caseIndex}), ...
        'RectangularFPC:ManufacturingInputContract');
end
end

function testAllQualificationSwitchesAreRequiredForTwoAndFourLayers(testCase)
requiredNames = { ...
    'enableExactSelfIntersectionCheck', ...
    'enableCopperClearanceCheck', ...
    'enableBoardAngleCheck', ...
    'enableCopperAngleCheck', ...
    'enablePadClearanceCheck', ...
    'enableViaClearanceCheck', ...
    'enableDxfReadbackCheck'};

for layerCount = [2, 4]
    result = rectangular_fpc_main(struct( ...
        'analysisOnly', true, ...
        'layerCount', layerCount, ...
        'turnsPerLayer', 1, ...
        'enablePreview', false, ...
        'enableFigure', false));
    input = manufacturingInputFromResult(result);
    for checkIndex = 1:numel(requiredNames)
        cfg = result.config;
        cfg.(requiredNames{checkIndex}) = false;
        report = rectangular_fpc_manufacturing('check_result', cfg, input);
        qualification = report.checks(strcmp( ...
            {report.checks.id}, 'REQUIRED_VALIDATION_CHECKS'));

        assertNumElements(testCase, qualification, 1);
        verifyEqual(testCase, qualification.status, 'FAIL', ...
            sprintf('%d-layer %s', layerCount, requiredNames{checkIndex}));
        verifyEqual(testCase, qualification.code, ...
            'REQUIRED_CHECK_DISABLED');
        verifyFalse(testCase, report.verified);
        verifyFalse(testCase, report.exportAllowed);
    end
end
end

function input = manufacturingInputFromResult(result)
input = struct( ...
    'minCopperSpacing', result.validation.minCopperSpacingMm, ...
    'minCopperToBoardMm', result.validation.minCopperToBoardMm, ...
    'minPadToUnrelatedTraceMm', result.validation.minPadToUnrelatedTraceMm, ...
    'minViaToUnrelatedCopperMm', result.validation.minViaToUnrelatedCopperMm, ...
    'minDrillToNonConnectedCopperMm', ...
        result.validation.minDrillToNonConnectedCopperMm, ...
    'minDrillToBoardMm', result.validation.minDrillToBoardMm, ...
    'vias', result.vias, ...
    'viaNonConnectedCopperPassed', ...
        result.validation.viaNonConnectedCopperPassed);
end
