function tests = test_rectangular_fpc_export_contracts
% Formal artifact readback contracts that exercise existing output trees.
tests = functiontests(localfunctions);
end

function testCoordinateCsvManufacturingFieldsAreReadBack(testCase)
paths = makeFormalOutput(false);
cleanup = onCleanup(@() removeTree(paths.root));
filename = fullfile(paths.result.outputPath, 'reports', ...
    '01_pad_via_coordinates.csv');
baseline = readtable(filename, 'TextType', 'string');
viaRow = 2;
mutations = { ...
    @(data) setNumeric(data, 'pad_diameter_mm', viaRow, 0.1), ...
    @(data) setNumeric(data, 'drill_diameter_mm', viaRow, 0.1), ...
    @(data) setNumeric(data, 'annular_ring_mm', viaRow, 0.1), ...
    @(data) setNumeric(data, 'antipad_diameter_mm', viaRow, 0.1), ...
    @(data) setText(data, 'from_layer', viaRow, "L99"), ...
    @(data) setText(data, 'to_layer', viaRow, "L99"), ...
    @(data) setText(data, 'object_type', viaRow, "tampered_type"), ...
    @(data) setText(data, 'placement_region', viaRow, "tampered_region"), ...
    @(data) setText(data, 'placement_mode', viaRow, "tampered_mode"), ...
    @(data) setText(data, 'description', viaRow, "tampered_description")};

for mutationIndex = 1:numel(mutations)
    writetable(mutations{mutationIndex}(baseline), filename);
    verifyError(testCase, @() verifyExistingOutput(paths), ...
        'RectangularFPC:ExportReadbackFailed');
end
end

function testMalformedOrEmptySvgIsRejectedByProductionReadback(testCase)
paths = makeFormalOutput(true);
cleanup = onCleanup(@() removeTree(paths.root));
filename = fullfile(paths.result.outputPath, 'previews', ...
    '01_preview_full.svg');
baselineSvg = fileread(filename);
verifyFalse(testCase, contains(baselineSvg, '>data1</text>'), ...
    'Preview legend must not expose MATLAB auto-generated series names.');
invalidDocuments = { ...
    '<svg', ...
    '<svg xmlns="http://www.w3.org/2000/svg"></svg>', ...
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"><path/></svg>', ...
    ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1">', ...
     '<path d="M0 0 L0 0"/></svg>'], ...
    ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="garbage">', ...
     '<path d="M0 0 L1 1"/></svg>'], ...
    ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1">', ...
     '<script>alert(1)</script><path d="M0 0 L1 1"/></svg>'], ...
    ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1">', ...
     '<foreignObject/><path d="M0 0 L1 1"/></svg>'], ...
    ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1">', ...
     '<path onload="alert(1)" d="M0 0 L1 1"/></svg>'], ...
    ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1">', ...
     '<a href="javascript:alert(1)"><path d="M0 0 L1 1"/></a></svg>']};
for documentIndex = 1:numel(invalidDocuments)
    fid = fopen(filename, 'w');
    fileCleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', invalidDocuments{documentIndex});
    clear fileCleanup;
    verifyError(testCase, @() verifyReadableOutput(paths), ...
        'RectangularFPC:ExportReadbackFailed');
end
end

function testGenerationStatusManufacturingFieldsAreReadBack(testCase)
paths = makeFormalOutput(false);
cleanup = onCleanup(@() removeTree(paths.root));
filename = fullfile(paths.result.outputPath, 'generation_status.txt');
baseline = fileread(filename);
expected = { ...
    paths.result.manufacturing.profile, ...
    paths.result.manufacturing.tier, ...
    paths.result.manufacturing.status, ...
    paths.result.manufacturing.applicability, ...
    sprintf('%d', paths.result.manufacturing.verified)};
fields = { ...
    'ManufacturingProfile', ...
    'ManufacturingTier', ...
    'ManufacturingStatus', ...
    'ManufacturingApplicability', ...
    'ManufacturingVerified'};
replacements = {'tampered', 'tampered', 'FAIL', 'CUSTOM_RULES', '0'};
for fieldIndex = 1:numel(fields)
    originalLine = sprintf('%s: %s', fields{fieldIndex}, expected{fieldIndex});
    replacementLine = sprintf('%s: %s', ...
        fields{fieldIndex}, replacements{fieldIndex});
    tampered = strrep(baseline, originalLine, replacementLine);
    assertNotEqual(testCase, tampered, baseline);
    writeTextFile(filename, tampered);
    verifyError(testCase, @() verifyExistingOutput(paths), ...
        'RectangularFPC:ExportReadbackFailed');
end
writeTextFile(filename, sprintf('%sManufacturingVerified: 0\n', baseline));
verifyError(testCase, @() verifyExistingOutput(paths), ...
    'RectangularFPC:ExportReadbackFailed');
end

function testCustomRulesKeepSupportedThroughViaFabricationNotes(testCase)
paths = makeFormalOutput(false, struct( ...
    'manufacturingRuleOverrides', struct('minTraceWidthMm', 0.10)));
cleanup = onCleanup(@() removeTree(paths.root));
verifyEqual(testCase, paths.result.manufacturing.applicability, ...
    'CUSTOM_RULES');
verifyFalse(testCase, paths.result.manufacturing.verified);
notes = fileread(fullfile(paths.result.outputPath, 'reports', ...
    '07_fabrication_notes.txt'));
verifyTrue(testCase, contains(notes, ...
    'All vias are plated through holes through the complete stack.'));
verifyFalse(testCase, contains(notes, ...
    'series interconnects use an unverified adjacent-layer via model'));
verifyTrue(testCase, contains(notes, ...
    'Requested profile: jlc_fpc_1oz'));
verifyTrue(testCase, contains(notes, 'Base profile: jlc_fpc_1oz'));
verifyTrue(testCase, contains(notes, ...
    'Rule classification: CUSTOM_RELAXED'));
verifyTrue(testCase, contains(notes, ...
    'BaseRule.minTraceWidthMm: 0.102'));
verifyTrue(testCase, contains(notes, ...
    'EffectiveRule.minTraceWidthMm: 0.1'));
verifyTrue(testCase, contains(notes, ...
    'RuleOverride.minTraceWidthMm: 0.1'));
tampered = strrep(notes, 'BaseRule.minTraceWidthMm: 0.102', ...
    'BaseRule.minTraceWidthMm: 0.1');
writeTextFile(fullfile(paths.result.outputPath, 'reports', ...
    '07_fabrication_notes.txt'), tampered);
verifyError(testCase, @() verifyReadableOutput(paths), ...
    'RectangularFPC:ExportReadbackFailed');
end

function testTwoLayerNotApplicableManufacturingRowRoundTrips(testCase)
paths = makeFormalOutput(false, struct('layerCount', 2));
cleanup = onCleanup(@() removeTree(paths.root));
data = readtable(fullfile(paths.result.outputPath, 'reports', ...
    '06_manufacturing_check.csv'), 'TextType', 'string');
row = data(data.check_id == "DRILL_TO_COPPER", :);
verifyEqual(testCase, height(row), 1);
verifyEqual(testCase, row.status, "NOT_APPLICABLE");
verifyTrue(testCase, isnan(row.measured_mm));
verifyEqual(testCase, row.code, "NOT_APPLICABLE");
end

function testCoordinateCsvPreservesLegalSubMillimeterPrecision(testCase)
paths = makeFormalOutput(false, struct('padDiameter', 1.5004));
cleanup = onCleanup(@() removeTree(paths.root));
data = readtable(fullfile(paths.result.outputPath, 'reports', ...
    '01_pad_via_coordinates.csv'), 'TextType', 'string');
padRows = data.object_type == "pad";
verifyEqual(testCase, data.pad_diameter_mm(padRows), ...
    repmat(1.5004, nnz(padRows), 1), 'AbsTol', 1e-12);
end

function testManufacturingCsvPreservesLargeMagnitudePrecision(testCase)
paths = makeScaledFormalOutput(100);
cleanup = onCleanup(@() removeTree(paths.root));
data = readtable(fullfile(paths.result.outputPath, 'reports', ...
    '06_manufacturing_check.csv'), 'TextType', 'string');
row = data(data.check_id == "TRACE_WIDTH", :);
verifyEqual(testCase, height(row), 1);
verifyEqual(testCase, row.measured_mm, 20.00000004, 'AbsTol', 1e-12);
end

function testRelativeOutputRootPublishesCanonicalOutputPaths(testCase)
workspaceRoot = tempname;
mkdir(workspaceRoot);
originalFolder = pwd;
cleanup = onCleanup(@() cleanupRelativeWorkspace( ...
    originalFolder, workspaceRoot));
cd(workspaceRoot);
result = rectangular_fpc_main(struct( ...
    'outputRoot', 'relative_output', ...
    'designName', 'relative_output_contract', ...
    'turnsPerLayer', 1, ...
    'enablePreview', false, ...
    'enableFigure', false));
expectedRoot = char(java.io.File(fullfile( ...
    workspaceRoot, 'relative_output')).getCanonicalPath());
verifyTrue(testCase, startsWith(result.outputPath, ...
    [expectedRoot filesep]));
verifyTrue(testCase, isfolder(result.outputPath));
verifyTrue(testCase, isfile(result.fileManifest));
end

function testFabricationNotesPreserveActionableTraceWidth(testCase)
paths = makeFormalOutput(false, struct('traceWidth', 0.2004));
cleanup = onCleanup(@() removeTree(paths.root));
notes = fileread(fullfile(paths.result.outputPath, 'reports', ...
    '07_fabrication_notes.txt'));
summary = fileread(fullfile(paths.result.outputPath, 'reports', ...
    '03_design_summary.txt'));
verifyTrue(testCase, contains(notes, 'assign 0.2004 mm trace width.'));
verifyTrue(testCase, contains(notes, ...
    'Trace width / spacing: 0.2004 / 0.15 mm'));
verifyTrue(testCase, contains(summary, ...
    'Trace width / spacing: 0.2004 / 0.15 mm'));
end

function paths = makeFormalOutput(enablePreview, extraOverrides)
if nargin < 2
    extraOverrides = struct();
end
paths.root = tempname;
outputRoot = fullfile(paths.root, 'output');
overrides = struct( ...
    'outputRoot', outputRoot, ...
    'designName', 'export_contract', ...
    'turnsPerLayer', 1, ...
    'enablePreview', enablePreview, ...
    'enableFigure', false);
names = fieldnames(extraOverrides);
for nameIndex = 1:numel(names)
    overrides.(names{nameIndex}) = extraOverrides.(names{nameIndex});
end
paths.result = rectangular_fpc_main(overrides);
paths.cfg = paths.result.config;
paths.cfg.designName = sprintf('%s_%s', ...
    paths.result.logicalDesignName, paths.result.runTimestamp);
end

function paths = makeScaledFormalOutput(scale)
cfg = rectangular_fpc_default_config();
lengthFields = { ...
    'plateLength', 'plateWidth', 'plateCornerRadius', ...
    'tabLength', 'tabWidth', 'tabOuterCornerRadius', ...
    'tabTransitionRadius', 'tabEdgeMargin', ...
    'traceWidth', 'traceSpacing', 'pitchMargin', 'edgeClearance', ...
    'minInnerWidth', 'minInnerLength', 'minSpiralCornerRadius', ...
    'leadYOffset', 'leadBendRadius', 'padTipInset', 'padDiameter', ...
    'padTipMargin', 'leadTabClearance', 'padToPadClearance', ...
    'padToCopperClearance', 'viaDrillDiameter', 'viaPadDiameter', ...
    'viaToCopperClearance', 'viaToBoardClearance', ...
    'viaToViaClearance', 'viaToPadClearance', ...
    'viaLandingLeadLength', 'viaLandingClearance', ...
    'viaInnerBendRadius', 'viaOuterLandingLeadLength', ...
    'viaOuterLandingClearance', 'viaOuterBendRadius', ...
    'innerViaPitch', 'innerViaRowOffsetY', ...
    'outerViaPitch', 'outerViaRowOffsetY', ...
    'viaKeepoutMargin', 'autoViaGridStep', 'outputViaTipInset', ...
    'outputViaAntiPadDiameter', 'outputViaToCopperClearance', ...
    'outputViaToBoardClearance'};
for fieldIndex = 1:numel(lengthFields)
    name = lengthFields{fieldIndex};
    cfg.(name) = cfg.(name) * scale;
end
cfg.traceWidth = 20.00000004;
cfg.turnsPerLayer = 1;
cfg.enablePreview = false;
cfg.enableFigure = false;
paths.root = tempname;
cfg.outputRoot = fullfile(paths.root, 'output');
cfg.designName = 'mfg_precision_contract';
paths.result = rectangular_fpc_main(cfg);
paths.cfg = paths.result.config;
paths.cfg.designName = sprintf('%s_%s', ...
    paths.result.logicalDesignName, paths.result.runTimestamp);
end

function verifyExistingOutput(paths)
rectangular_fpc_export('verify_output', paths.cfg, paths.result, ...
    paths.result.outputPath);
end

function verifyReadableOutput(paths)
rectangular_fpc_export_verification('readable_artifact_set', ...
    paths.result.outputPath, paths.cfg, paths.result);
end

function data = setNumeric(data, name, row, delta)
data.(name)(row) = data.(name)(row) + delta;
end

function data = setText(data, name, row, value)
data.(name)(row) = value;
end

function writeTextFile(filename, content)
fid = fopen(filename, 'w', 'n', 'UTF-8');
assert(fid ~= -1, 'Unable to open export-contract fixture.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', content);
clear cleanup;
end

function removeTree(root)
if isfolder(root)
    rmdir(root, 's');
end
end

function cleanupRelativeWorkspace(originalFolder, workspaceRoot)
cd(originalFolder);
removeTree(workspaceRoot);
end
