function tests = test_rectangular_fpc_private_contracts
% Direct contracts for private manufacturing decisions.
tests = functiontests(localfunctions);
end

function testSupportedProfileRejectsAdjacentLayerVia(testCase)
result = rectangular_fpc_main(struct( ...
    'analysisOnly', true, ...
    'layerCount', 4, ...
    'turnsPerLayer', 1, ...
    'enablePreview', false, ...
    'enableFigure', false));
manufacturingInput = struct( ...
    'minCopperSpacing', result.validation.minCopperSpacingMm, ...
    'minCopperToBoardMm', result.validation.minCopperToBoardMm, ...
    'vias', result.vias, ...
    'viaNonConnectedCopperPassed', ...
        result.validation.viaNonConnectedCopperPassed);

baseline = rectangular_fpc_manufacturing( ...
    'check_result', result.config, manufacturingInput);
baselineTechnology = baseline.checks( ...
    strcmp({baseline.checks.id}, 'VIA_TECHNOLOGY'));
assertNumElements(testCase, baselineTechnology, 1);
verifyEqual(testCase, baselineTechnology.status, 'PASS');

manufacturingInput.vias(1).type = 'adjacent_layer_via';

report = rectangular_fpc_manufacturing( ...
    'check_result', result.config, manufacturingInput);
viaTechnology = report.checks(strcmp({report.checks.id}, 'VIA_TECHNOLOGY'));

assertNumElements(testCase, viaTechnology, 1);
verifyEqual(testCase, viaTechnology.status, 'FAIL');
verifyEqual(testCase, viaTechnology.code, 'UNSUPPORTED_VIA_TECHNOLOGY');
verifyFalse(testCase, report.exportAllowed);
verifyFalse(testCase, report.verified);
end

function testCheckResultRejectsMissingCopperToBoardMeasurement(testCase)
% P2 契约：check_result 缺少实测 minCopperToBoardMm 时必须 fail closed，
% 不允许静默回退到 cfg.edgeClearance（防止再次引入 H2 假 PASS）。
result = rectangular_fpc_main(struct( ...
    'analysisOnly', true, ...
    'layerCount', 2, ...
    'turnsPerLayer', 1, ...
    'enablePreview', false, ...
    'enableFigure', false));
manufacturingInput = struct( ...
    'minCopperSpacing', result.validation.minCopperSpacingMm, ...
    'vias', result.vias, ...
    'viaNonConnectedCopperPassed', ...
        result.validation.viaNonConnectedCopperPassed);
verifyError(testCase, @() rectangular_fpc_manufacturing( ...
    'check_result', result.config, manufacturingInput), ...
    'RectangularFPC:ManufacturingInputContract');
end

function testCheckResultRejectsIncompleteManufacturingInput(testCase)
% L1 回归：check_result 输入契约覆盖全部实测字段，缺任一即 fail closed；
% 尤其缺 vias 时不得静默跳过 VIA_TECHNOLOGY 资格行。
result = rectangular_fpc_main(struct( ...
    'analysisOnly', true, 'layerCount', 2, 'turnsPerLayer', 1, ...
    'enablePreview', false, 'enableFigure', false));
base = struct( ...
    'minCopperSpacing', result.validation.minCopperSpacingMm, ...
    'minCopperToBoardMm', result.validation.minCopperToBoardMm, ...
    'vias', result.vias, ...
    'viaNonConnectedCopperPassed', result.validation.viaNonConnectedCopperPassed);
missingSpacing = rmfield(base, 'minCopperSpacing');
missingBoard = rmfield(base, 'minCopperToBoardMm');
missingVias = rmfield(base, 'vias');
missingVerdict = rmfield(base, 'viaNonConnectedCopperPassed');
emptyVias = base;
emptyVias.vias = struct([]);
cases = {missingSpacing, missingBoard, missingVias, missingVerdict, emptyVias};
for caseIndex = 1:numel(cases)
    verifyError(testCase, @() rectangular_fpc_manufacturing( ...
        'check_result', result.config, cases{caseIndex}), ...
        'RectangularFPC:ManufacturingInputContract');
end
end
