function tests = test_rectangular_fpc_private_contracts
% Direct contracts for private manufacturing decisions.
tests = functiontests(localfunctions);
end

function testSupportedProfileRejectsAdjacentLayerVia(testCase)
result = rectangular_fpc_main(struct( ...
    'analysisOnly', true, ...
    'layerCount', 4, ...
    'turnsPerLayer', 1, ...
    'enablePreview', false, ...
    'enableFigure', false));
manufacturingInput = struct( ...
    'minCopperSpacing', result.validation.minCopperSpacingMm, ...
    'vias', result.vias, ...
    'viaNonConnectedCopperPassed', ...
        result.validation.viaNonConnectedCopperPassed);

baseline = rectangular_fpc_manufacturing( ...
    'check_result', result.config, manufacturingInput);
baselineTechnology = baseline.checks( ...
    strcmp({baseline.checks.id}, 'VIA_TECHNOLOGY'));
assertNumElements(testCase, baselineTechnology, 1);
verifyEqual(testCase, baselineTechnology.status, 'PASS');

manufacturingInput.vias(1).type = 'adjacent_layer_via';

report = rectangular_fpc_manufacturing( ...
    'check_result', result.config, manufacturingInput);
viaTechnology = report.checks(strcmp({report.checks.id}, 'VIA_TECHNOLOGY'));

assertNumElements(testCase, viaTechnology, 1);
verifyEqual(testCase, viaTechnology.status, 'FAIL');
verifyEqual(testCase, viaTechnology.code, 'UNSUPPORTED_VIA_TECHNOLOGY');
verifyFalse(testCase, report.exportAllowed);
verifyFalse(testCase, report.verified);
end
