function varargout = rectangular_fpc_config_validation(operation, varargin)
%RECTANGULAR_FPC_CONFIG_VALIDATION Configuration normalization and checks.

switch operation
    case 'config'
        [varargout{1:nargout}] = validateConfig(varargin{:});
    otherwise
        error('RectangularFPC:UnknownConfigValidationOperation', ...
            'Unknown config-validation operation: %s', operation);
end
end

function cfg = validateConfig(cfg)
%FPC_COIL_VALIDATE_CONFIG Validate and normalize a complete configuration.

if ~isstruct(cfg) || ~isscalar(cfg)
    error('RectangularFPC:InvalidConfig', 'cfg must be a scalar struct.');
end

required = fieldnames(rectangular_fpc_default_config());
for k = 1:numel(required)
    if ~isfield(cfg, required{k})
        error('RectangularFPC:MissingConfigField', ...
            'cfg is missing required field "%s".', required{k});
    end
end

scalarNumeric = { ...
    'layerCount', 'maxLayerCount', 'turnsPerLayer', ...
    'plateLength', 'plateWidth', 'plateCornerRadius', ...
    'tabLength', 'tabWidth', 'tabOuterCornerRadius', ...
    'tabTransitionRadius', 'tabEdgeMargin', ...
    'traceWidth', 'traceSpacing', 'pitchMargin', 'edgeClearance', ...
    'minInnerWidth', 'minInnerLength', 'minSpiralCornerRadius', ...
    'leadYOffset', 'leadBendRadius', 'leadArcPointCount', ...
    'padTipInset', 'padDiameter', 'padTipMargin', 'leadTabClearance', ...
    'padToPadClearance', 'padToCopperClearance', ...
    'viaDrillDiameter', 'viaPadDiameter', ...
    'viaToCopperClearance', 'viaToBoardClearance', ...
    'viaToViaClearance', 'viaToPadClearance', ...
    'viaLandingLeadLength', 'viaLandingClearance', 'viaInnerBendRadius', ...
    'viaOuterLandingLeadLength', 'viaOuterLandingClearance', ...
    'viaOuterBendRadius', 'outputViaTipInset', ...
    'outputViaAntiPadDiameter', 'outputViaToCopperClearance', ...
    'outputViaToBoardClearance', ...
    'innerViaPitch', 'innerViaRowOffsetY', ...
    'outerViaPitch', 'outerViaRowOffsetY', ...
    'viaKeepoutMargin', 'autoViaGridStep', 'recommendedTurnMargin', ...
    'connectionPhase', ...
    'copperThickness', 'copperResistivity', 'minAnnularRing', ...
    'minCopperInteriorAngleDeg', ...
    'minBoardInteriorAngleDeg', 'angleToleranceDeg', ...
    'geometryTolerance', 'connectionTolerance', 'clearanceTolerance', ...
    'crossProductTolerance', 'parameterTolerance', ...
    'pointsPerTurn', 'minTurnPointCount', 'boardArcPointCount', ...
    'maxVerticesPerDxfEntity'};
for k = 1:numel(scalarNumeric)
    name = scalarNumeric{k};
    value = cfg.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
            ~isfinite(value)
        error('RectangularFPC:InvalidConfigValue', ...
            'cfg.%s must be a finite real numeric scalar.', name);
    end
end

allowedLayerCounts = [2, 4, 6, 8];
if ~ismember(cfg.layerCount, allowedLayerCounts) || ...
        cfg.layerCount > cfg.maxLayerCount
    error('RectangularFPC:InvalidLayerCount', ...
        ['layerCount=%g is invalid; supported even values (偶数) are ', ...
         '2, 4, 6, or 8 and must not exceed maxLayerCount=%g.'], ...
        cfg.layerCount, cfg.maxLayerCount);
end
if ~ismember(cfg.maxLayerCount, allowedLayerCounts)
    error('RectangularFPC:InvalidLayerCount', ...
        'maxLayerCount=%g must be one of 2, 4, 6, or 8.', ...
        cfg.maxLayerCount);
end
if cfg.turnsPerLayer < 1 || cfg.turnsPerLayer ~= floor(cfg.turnsPerLayer)
    error('RectangularFPC:InvalidTurns', 'turnsPerLayer must be a positive integer.');
end

% New turn-limit and via-planning scalar constraints.
if cfg.connectionPhase < 0 || cfg.connectionPhase > 1
    error('RectangularFPC:InvalidConfigValue', ...
        'connectionPhase must be within [0, 1] (normalized phase).');
end
if cfg.recommendedTurnMargin < 0 || cfg.recommendedTurnMargin ~= floor(cfg.recommendedTurnMargin)
    error('RectangularFPC:InvalidConfigValue', ...
        'recommendedTurnMargin must be a non-negative integer.');
end

% String enumeration fields.
enumFields = { ...
    'connectionSide', {'right_center'}; ...
    'coilOuterCornerRadiusMode', {'follow_board','maximize','manual'}; ...
    'cornerOffsetMode', {'strict_concentric','legacy_clamped'}; ...
    'coordinateOrigin', {'body_lower_left'}; ...
    'viaPlacementMode', {'legacy_auto','hybrid_auto','manual'}; ...
    'innerViaLayout', {'horizontal'}; ...
    'outerViaLayout', {'horizontal'}; ...
    'outputViaPlacementMode', {'auto','manual'}; ...
    'manufacturingProfile', {'jlc_fpc_1oz'}; ...
    'manufacturingTier', {'standard','extreme'}};
for k = 1:size(enumFields, 1)
    name = enumFields{k,1};
    value = cfg.(name);
    if ~isTextScalar(value) || ~ismember(char(value), enumFields{k,2})
        allowed = strjoin(enumFields{k,2}, ', ');
        error('RectangularFPC:InvalidConfigValue', ...
            'cfg.%s must be one of: %s.', name, allowed);
    end
    cfg.(name) = char(value);
end

% coilOuterCornerRadius: empty by default; manual mode requires a valid scalar.
if isempty(cfg.coilOuterCornerRadius)
    if strcmp(cfg.coilOuterCornerRadiusMode, 'manual')
        error('RectangularFPC:InvalidConfigValue', ...
            'coilOuterCornerRadius must be provided when coilOuterCornerRadiusMode is ''manual''.');
    end
else
    if ~isnumeric(cfg.coilOuterCornerRadius) || ...
            ~isscalar(cfg.coilOuterCornerRadius) || ...
            ~isreal(cfg.coilOuterCornerRadius) || ...
            ~isfinite(cfg.coilOuterCornerRadius) || ...
            cfg.coilOuterCornerRadius <= 0
        error('RectangularFPC:InvalidConfigValue', ...
            'cfg.coilOuterCornerRadius must be a positive finite real scalar.');
    end
    outerCenterInset = cfg.edgeClearance + cfg.traceWidth/2;
    outerLength = cfg.plateLength - 2*outerCenterInset;
    outerWidth = cfg.plateWidth - 2*outerCenterInset;
    if cfg.coilOuterCornerRadius > min(outerLength, outerWidth)/2
        error('RectangularFPC:InvalidConfigValue', ...
            'coilOuterCornerRadius=%g exceeds min(outerLength,outerWidth)/2=%g.', ...
            cfg.coilOuterCornerRadius, min(outerLength, outerWidth)/2);
    end
end

% Manual via coordinate matrices: empty allowed when not in manual mode.
for name = {'manualSeriesViaXY', 'manualOutputViaXY'}
    value = cfg.(name{1});
    if isempty(value)
        continue
    end
    if ~isnumeric(value) || size(value, 2) ~= 2 || ~all(isfinite(value), 'all')
        error('RectangularFPC:InvalidConfigValue', ...
            'cfg.%s must be an Nx2 finite numeric matrix (mm).', name{1});
    end
    cfg.(name{1}) = double(value);
end

% Manual mode row-count checks.
if strcmp(cfg.viaPlacementMode, 'manual')
    if size(cfg.manualSeriesViaXY, 1) ~= cfg.layerCount - 1
        error('RectangularFPC:InvalidManualVias', ...
            ['manualSeriesViaXY must have exactly layerCount-1=%d rows ', ...
             '(V12, V23, ...) when viaPlacementMode is ''manual''; got %d.'], ...
            cfg.layerCount - 1, size(cfg.manualSeriesViaXY, 1));
    end
end
if strcmp(cfg.outputViaPlacementMode, 'manual')
    if ~isequal(size(cfg.manualOutputViaXY), [1, 2])
        error('RectangularFPC:InvalidManualVias', ...
            'manualOutputViaXY must be a 1x2 matrix when outputViaPlacementMode is ''manual''.');
    end
end

positive = {'plateLength','plateWidth','tabLength','tabWidth','traceWidth', ...
    'minInnerWidth','minInnerLength','minSpiralCornerRadius','leadYOffset','leadBendRadius','padTipInset', ...
    'padDiameter','viaDrillDiameter','viaPadDiameter', ...
    'viaLandingLeadLength','viaInnerBendRadius', ...
    'viaOuterLandingLeadLength','viaOuterBendRadius', ...
    'outputViaTipInset','copperThickness', ...
    'copperResistivity','geometryTolerance','connectionTolerance', ...
    'crossProductTolerance','parameterTolerance','pitchMargin', ...
    'innerViaPitch','outerViaPitch','autoViaGridStep'};
for k = 1:numel(positive)
    if cfg.(positive{k}) <= 0
        error('RectangularFPC:InvalidConfigValue', 'cfg.%s must be greater than zero.', positive{k});
    end
end

nonnegative = {'plateCornerRadius','tabOuterCornerRadius','tabEdgeMargin', ...
    'traceSpacing','edgeClearance','padTipMargin','leadTabClearance', ...
    'padToPadClearance','padToCopperClearance','viaToCopperClearance', ...
    'viaToBoardClearance','viaToViaClearance','viaToPadClearance', ...
    'viaLandingClearance','viaOuterLandingClearance', ...
    'outputViaToCopperClearance','outputViaToBoardClearance', ...
    'minAnnularRing','clearanceTolerance'};
for k = 1:numel(nonnegative)
    if cfg.(nonnegative{k}) < 0
        error('RectangularFPC:InvalidConfigValue', 'cfg.%s cannot be negative.', nonnegative{k});
    end
end

if cfg.viaPadDiameter <= cfg.viaDrillDiameter || ...
        (cfg.viaPadDiameter - cfg.viaDrillDiameter)/2 + ...
        cfg.geometryTolerance < cfg.minAnnularRing
    error('RectangularFPC:InvalidViaGeometry', ...
        'Via pad/drill dimensions do not provide minAnnularRing.');
end
if cfg.outputViaAntiPadDiameter <= cfg.viaPadDiameter
    error('RectangularFPC:InvalidViaGeometry', ...
        'outputViaAntiPadDiameter must exceed viaPadDiameter.');
end
if ~isTextScalar(cfg.outputViaType) || ...
        ~strcmp(char(cfg.outputViaType), 'through_via')
    error('RectangularFPC:InvalidConfigValue', ...
        'outputViaType must be ''through_via'' for the L%d-to-L1 output.', cfg.layerCount);
end
if ~isTextScalar(cfg.viaClearanceSeverity) || ...
        ~ismember(char(cfg.viaClearanceSeverity), {'warning','error'})
    error('RectangularFPC:InvalidConfigValue', ...
        'viaClearanceSeverity must be ''warning'' or ''error''.');
end
cfg.outputViaType = char(cfg.outputViaType);
cfg.viaClearanceSeverity = char(cfg.viaClearanceSeverity);

integerAtLeast = { ...
    'leadArcPointCount', 8; 'pointsPerTurn', 100; ...
    'minTurnPointCount', 100; 'boardArcPointCount', 8; ...
    'maxVerticesPerDxfEntity', 2};
for k = 1:size(integerAtLeast, 1)
    name = integerAtLeast{k,1};
    lowerBound = integerAtLeast{k,2};
    if cfg.(name) < lowerBound || cfg.(name) ~= floor(cfg.(name))
        error('RectangularFPC:InvalidConfigValue', ...
            'cfg.%s must be an integer >= %d.', name, lowerBound);
    end
end

booleanFields = {'useRecommendedTurns','enablePreview','enableFigure','analysisOnly', ...
    'requireSmoothLeadTransitions', ...
    'enableExactSelfIntersectionCheck','enableCopperClearanceCheck', ...
    'enableBoardAngleCheck','enableCopperAngleCheck', ...
    'enablePadClearanceCheck','enableViaClearanceCheck', ...
    'enableDxfReadbackCheck'};
for k = 1:numel(booleanFields)
    value = cfg.(booleanFields{k});
    if ~isscalar(value) || (~islogical(value) && ...
            ~(isnumeric(value) && ismember(value, [0, 1])))
        error('RectangularFPC:InvalidConfigValue', ...
            'cfg.%s must be logical or numeric 0/1.', booleanFields{k});
    end
    cfg.(booleanFields{k}) = logical(value);
end

rectangular_fpc_manufacturing('validate_config', cfg);

if ~isTextScalar(cfg.outputRoot) || ~isTextScalar(cfg.designName)
    error('RectangularFPC:InvalidOutputName', ...
        'outputRoot and designName must be character vectors or string scalars.');
end
cfg.outputRoot = char(cfg.outputRoot);
cfg.designName = char(cfg.designName);
if isempty(cfg.outputRoot) || isempty(cfg.designName) || ...
        isempty(regexp(cfg.designName, '^[A-Za-z0-9_-]+$', 'once'))
    error('RectangularFPC:InvalidOutputName', ...
        'outputRoot must be nonempty and designName may contain only letters, numbers, _ and -.');
end

end

function tf = isTextScalar(value)

tf = ischar(value) || (isstring(value) && isscalar(value));

end
