function result = rectangular_fpc_engine(cfg)
%RECTANGULAR_FPC_ENGINE Side-effect-free rectangular-coil orchestration.
% 两层至八层矩形 FPC 线圈共享分析核心。
%
% 输入：
%   cfg - 由 rectangular_fpc_main 传入的参数结构体。
%
% 输出：
%   result - 包含验证结论和输出目录的结构体。
%
% 流程：
%   生成几何 -> 全部检查 -> 制造资格判定 -> 返回只读分析结果。

if ~cfg.analysisOnly
    error('RectangularFPC:InternalContract', ...
        'The analysis engine is side-effect free and requires analysisOnly=true.');
end

try

%% =========================================================
% 1. cfg字段完整性和参数合法性检查
%% =========================================================

cfg = rectangular_fpc_validation('config', cfg);

%% =========================================================
% 2. 派生参数计算
%% =========================================================

d = rectangular_fpc_geometry('derived_parameters', cfg);
limits = rectangular_fpc_geometry('turn_limits', cfg);
tol = cfg.geometryTolerance;

if cfg.tabWidth/2 < d.requiredHalfWidth
    error('RectangularFPC:InvalidTerminalGeometry', ...
        '尾部宽度不足，无法容纳焊盘和边缘裕量。');
end

if cfg.padTipInset < cfg.padDiameter/2 + cfg.padTipMargin
    error('RectangularFPC:InvalidTerminalGeometry', ...
        '焊盘距离尾部最右端过近。');
end

horizontalLeadLength = ...
    d.padA(1) - (d.outerRightCenterX + cfg.leadBendRadius);
if horizontalLeadLength < cfg.leadTabClearance
    error('RectangularFPC:InvalidTerminalGeometry', ...
        '尾部水平引线长度不足。');
end

if d.padA(1) - cfg.padDiameter/2 < d.bodyRightX
    error('RectangularFPC:InvalidTerminalGeometry', ...
        '焊盘超出尾部左边界。');
end

%% =========================================================
% 3. 最大匝数计算
%% =========================================================

analyticalMaxTurns = limits.analyticalMaximum;

% 理论宽度只回答“放不放得下”。正式推荐值还必须逐个候选执行
% 圆弧、角度、线距、自交、焊盘和过孔检查，因此两种上限分开保存。
boardXY = rectangular_fpc_geometry('board_outline', cfg);
boardXY = rectangular_fpc_geometry('remove_duplicates', boardXY, tol);
boardXY = rectangular_fpc_geometry('remove_zero_length', boardXY, tol);
if size(boardXY,1) > 1 && norm(boardXY(end,:)-boardXY(1,:)) < tol
    boardXY(end,:) = [];
end

[fullyValidatedMaxTurns, turnScan, validatedTurnCache] = ...
    calculateFullyValidatedMaximumTurns( ...
    cfg, d, boardXY, analyticalMaxTurns, limits);
if fullyValidatedMaxTurns < 1
    if isempty(turnScan)
        scanReason = '未生成候选结果';
    else
        scanReason = turnScan(end).failureReason;
    end
    % 手动过孔无效：直接以具体失败抛出（不降级为 NoValidTurnCount）
    if ~isempty(strfind(scanReason, '手动坐标')) %#ok<STREMP>
        error('RectangularFPC:ViaPlanningFailed', scanReason);
    end
    error('RectangularFPC:NoValidTurnCount', ...
        '当前层数与制造约束下没有能够通过全部几何检查的匝数。最后失败原因：%s', ...
        scanReason);
end

if cfg.useRecommendedTurns
    % 推荐匝数 = 完整验证上限 - recommendedTurnMargin（默认保留 1 匝裕量）。
    cfg.turnsPerLayer = max(1, fullyValidatedMaxTurns - cfg.recommendedTurnMargin);
end

% 用户显式匝数的多重解析约束检查：宽度、长度、圆角、内圈过孔区域。
if cfg.turnsPerLayer > limits.width
    error('RectangularFPC:TurnLimitExceeded', ...
        ['当前主体宽度%.2f mm无法容纳每层%d匝。\n' ...
        '当前线宽/线距为%.2f/%.2f mm。\n' ...
        '中心至少保留%.2f mm时，宽度允许最大%d匝/层。\n' ...
        '右侧尾部不参与匝数计算。'], ...
        cfg.plateWidth, cfg.turnsPerLayer, ...
        cfg.traceWidth, cfg.traceSpacing, ...
        cfg.minInnerWidth, limits.width);
end
if cfg.turnsPerLayer > limits.length
    error('RectangularFPC:TurnLimitExceeded', ...
        ['长度方向上每层%d匝超过理论上限。\n' ...
        '长度允许最大%d匝/层（中心空白长度至少%.2f mm）。'], ...
        cfg.turnsPerLayer, limits.length, cfg.minInnerLength);
end
if strcmp(cfg.cornerOffsetMode, 'strict_concentric') && ...
        cfg.turnsPerLayer > limits.cornerRadius
    error('RectangularFPC:TurnLimitExceeded', ...
        ['宽度允许 %d 匝，但严格同心圆角仅允许 %d 匝。\n' ...
        '当前线圈外圈圆角半径为 %.3f mm，\n' ...
        '最小允许内圈圆角为 %.3f mm。\n' ...
        '可增大线圈外圈圆角、减小匝数或切换 legacy_clamped 模式。'], ...
        limits.width, limits.cornerRadius, ...
        limits.coilOuterRadius, cfg.minSpiralCornerRadius);
end
if cfg.turnsPerLayer > limits.innerViaRegion
    error('RectangularFPC:TurnLimitExceeded', ...
        ['内圈过孔区域允许最大%d匝/层，当前为%d匝。\n' ...
        '新增层间过孔及逃逸引线占用中心空白空间。'], ...
        limits.innerViaRegion, cfg.turnsPerLayer);
end
if ~limits.tabCapacityPass
    error('RectangularFPC:TabViaCapacityExceeded', ...
        '右侧尾板可用长度不足，无法容纳全部偶数编号层间过孔；\n建议增大 tabLength、减小过孔数量、改变过孔布局或使用手动坐标。');
end

innerCenterInset = d.outerCenterInset + cfg.turnsPerLayer*d.pitch;
innerLength = cfg.plateLength - 2*innerCenterInset;
innerWidth  = cfg.plateWidth  - 2*innerCenterInset;

if innerLength <= cfg.traceWidth || innerWidth <= cfg.traceWidth
    error('RectangularFPC:TurnLimitExceeded', ...
        '内圈尺寸无效，请减少匝数或增大主体宽度。');
end

%% =========================================================
% 4. 各层螺旋生成
%% =========================================================

if isfinite(validatedTurnCache.turns) && ...
        validatedTurnCache.turns == cfg.turnsPerLayer
    layerXY = validatedTurnCache.layerXY;
    layerPaths = validatedTurnCache.layerPaths;
    vias = validatedTurnCache.vias;
    connectionErrors = validatedTurnCache.connectionErrors;
    escapeArcFallback = validatedTurnCache.escapeArcFallback;
else
    [layerXY, layerPaths, vias, connectionErrors, escapeArcFallback] = ...
        rectangular_fpc_geometry('build_layers', cfg, d, limits, boardXY);
end
[~, layerPaths] = rectangular_fpc_geometry( ...
    'normalize_layers', layerXY, layerPaths, tol);
validation = rectangular_fpc_validation('design', ...
    cfg, d, boardXY, layerPaths, vias, connectionErrors, ...
    escapeArcFallback, limits, fullyValidatedMaxTurns);
minCopperSpacing = validation.minCopperSpacingMm;
manufacturingInput = struct( ...
    'minCopperSpacing', minCopperSpacing, ...
    'minCopperToBoardMm', validation.minCopperToBoardMm, ...
    'minPadToUnrelatedTraceMm', validation.minPadToUnrelatedTraceMm, ...
    'minViaToUnrelatedCopperMm', validation.minViaToUnrelatedCopperMm, ...
    'minDrillToNonConnectedCopperMm', ...
        validation.minDrillToNonConnectedCopperMm, ...
    'minDrillToBoardMm', validation.minDrillToBoardMm, ...
    'vias', vias, ...
    'viaNonConnectedCopperPassed', ...
    validation.viaNonConnectedCopperPassed);
manufacturing = rectangular_fpc_manufacturing( ...
    'check_result', cfg, manufacturingInput);
if ~validation.passed
    error('RectangularFPC:ValidationFailed', ...
        'Rectangular FPC validation failed: %s', ...
        strjoin(validation.messages, '; '));
end
%% =========================================================
% 5. 结果元数据组装（不写文件）
%% =========================================================

copperLayerNames = cell(cfg.layerCount, 1);
for k = 1:cfg.layerCount
    if k == 1
        copperLayerNames{k} = 'COPPER_L1_TOP';
    elseif k == cfg.layerCount
        copperLayerNames{k} = sprintf('COPPER_L%d_BOTTOM', k);
    else
        copperLayerNames{k} = sprintf('COPPER_L%d_INNER%d', k, k-1);
    end
end

catch ME
    rethrow(ME);
end

layers = repmat(struct( ...
    'index', 0, 'name', '', 'paths', {{}}, ...
    'dxfFile', '', 'centerlineDxfFile', '', ...
    'physicalCopperDxfFile', '', 'antipadKeepoutDxfFile', '', ...
    'legacyDxfFile', ''), ...
    cfg.layerCount, 1);
for k = 1:cfg.layerCount
    layers(k).index = k;
    layers(k).name = copperLayerNames{k};
    layers(k).paths = layerPaths{k};
end

pads = struct( ...
    'name', {'PAD_A', 'PAD_B'}, ...
    'xy', {d.padA, d.padB}, ...
    'layer', {1, 1}, ...
    'type', {'external_pad', 'external_pad'}, ...
    'diameter', cfg.padDiameter);

layerLengthMm = zeros(cfg.layerCount, 1);
for k = 1:cfg.layerCount
    layerLengthMm(k) = sum(cellfun(@(path) ...
        rectangular_fpc_geometry('path_length', path), layerPaths{k}));
end
totalLengthMm = sum(layerLengthMm);
crossSectionM2 = (cfg.traceWidth/1000)*(cfg.copperThickness/1000);
totalResistanceOhm = cfg.copperResistivity* ...
    (totalLengthMm/1000)/crossSectionM2;

coordinateCsv = '';
summaryPath = '';
validationPath = '';
turnScanPath = '';
outputFolder = '';

result = struct( ...
    'passed', true, ...
    'layerCount', cfg.layerCount, ...
    'turnsPerLayer', cfg.turnsPerLayer, ...
    'outputFolder', outputFolder, ...
    'outputPath', outputFolder, ...
    'runTimestamp', '', ...
    'config', cfg, ...
    'boardXY', boardXY, ...
    'layerPaths', {layerPaths}, ...
    'layers', layers, ...
    'vias', vias, ...
    'pads', pads, ...
    'validation', validation, ...
    'manufacturing', manufacturing, ...
    'turnScan', turnScan, ...
    'coordinateCsv', coordinateCsv, ...
    'summaryFile', summaryPath, ...
    'validationReport', validationPath, ...
    'turnScanFile', turnScanPath, ...
    'boardDxfFile', '', ...
    'drillMapDxfFile', '', ...
    'layerMappingFile', '', ...
    'manufacturingReport', '', ...
    'fabricationNotes', '', ...
    'fileManifest', '', ...
    'recommendedTurns', max(1, fullyValidatedMaxTurns - cfg.recommendedTurnMargin), ...
    'widthBasedMaximumTurns', limits.width, ...
    'lengthBasedMaximumTurns', limits.length, ...
    'cornerRadiusMaximumTurns', limits.cornerRadius, ...
    'innerViaRegionMaximumTurns', limits.innerViaRegion, ...
    'analyticalMaximumTurns', limits.analyticalMaximum, ...
    'fullyValidatedMaximumTurns', fullyValidatedMaxTurns, ...
    'turnLimits', limits, ...
    'minBoardAngle', validation.minBoardAngleDeg, ...
    'minCopperAngle', validation.minCopperAngleDeg, ...
    'minCopperSpacing', minCopperSpacing, ...
    'layerLengthMm', layerLengthMm, ...
    'totalLengthMm', totalLengthMm, ...
    'totalTraceLengthMm', totalLengthMm, ...
    'totalResistanceOhm', totalResistanceOhm, ...
    'estimatedDcResistanceOhm', totalResistanceOhm);

end

%% =========================================================
% 局部函数
%% =========================================================

function [maxTurns, scan, validatedTurnCache] = ...
    calculateFullyValidatedMaximumTurns( ...
    cfg, d, boardXY, analyticalMaxTurns, limits)

maxTurns = 0;
scan = repmat(struct('turns', 0, 'passed', false, ...
    'failureReason', ''), analyticalMaxTurns, 1);
scanCount = 0;
validatedTurnCache = struct();
validatedTurnCache.turns = NaN;
validatedTurnCache.layerXY = cell(0, 1);
validatedTurnCache.layerPaths = cell(0, 1);
validatedTurnCache.vias = struct([]);
validatedTurnCache.connectionErrors = [];
validatedTurnCache.escapeArcFallback = false;
% 从理论上限向下扫描；首个通过者就是当前配置的完整几何上限。
for turns = analyticalMaxTurns:-1:1
    candidateCfg = cfg;
    candidateCfg.turnsPerLayer = turns;
    [candidatePass, failureReason, candidateGeometry] = ...
        rectangular_fpc_validation( ...
        'candidate', candidateCfg, d, boardXY, limits);
    scanCount = scanCount + 1;
    scan(scanCount) = struct( ...
        'turns', turns, 'passed', candidatePass, ...
        'failureReason', failureReason);
    if candidatePass
        scan = scan(1:scanCount);
        maxTurns = turns;
        validatedTurnCache = candidateGeometry;
        validatedTurnCache.turns = turns;
        return;
    end
end

scan = scan(1:scanCount);

end

%% =========================================================
